require 'rake'
require 'rake/clean'
require 'rake/gempackagetask'
require 'rake/rdoctask'
require 'rake/testtask'
require 'fileutils'
include FileUtils

NAME = "dunelox-generator"
VERS = ENV['VERSION'] || "0.1"
PKG = "#{NAME}-#{VERS}"

RDOC_OPTS = ['--quiet', '--title', 'Dunelox Generator', '--main', 'README', '--inline-source']
PKG_FILES = %w(CHANGELOG COPYING README Rakefile) +
      Dir.glob("{bin,doc,test,lib,extras}/**/*")
puts PKG_FILES     
SPEC =
  Gem::Specification.new do |s|
    s.name = NAME
    s.version = VERS
    s.platform = Gem::Platform::RUBY
    s.has_rdoc = true
    s.rdoc_options += RDOC_OPTS
    s.extra_rdoc_files = ["README", "CHANGELOG", "COPYING"]
    s.summary = "an Adobe Flex source code generator reflecting on ActiveRecords"
    s.description = s.summary
    s.author = "Ernest Micklei"
    s.email = 'ernest.micklei@philemonworks.com'
    s.homepage = 'http://dunelox.googlecode.com'
    s.files = PKG_FILES
    s.require_paths = ["lib"]
    s.autorequire = "lib/dunelox-generator"
    s.executables = ["dunelox-setup"] 
  end

Rake::RDocTask.new do |rdoc|
    rdoc.rdoc_dir = 'doc/rdoc'
    rdoc.options += RDOC_OPTS
    rdoc.main = "README"
    rdoc.rdoc_files.add ['README', 'CHANGELOG', 'COPYING', 'lib/**/*.rb']
end

Rake::GemPackageTask.new(SPEC) do |p| end

task :install do
    Gem::GemRunner.new.run(['install','pkg/dunelox-generator'])
end

desc "Default Task"
task :default => [ :package ,:install ]